import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:geolocator/geolocator.dart';
import 'firebase_options.dart'; // This file was generated by flutterfire configure
import 'models/activity.dart'; // Ensure this matches your model file path

void main() async {
  // 1. Ensure Flutter bindings are initialized before Firebase
  WidgetsFlutterBinding.ensureInitialized();

  // 2. Initialize Firebase using the generated options
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  runApp(const ToddlerActivityApp());
}

class ToddlerActivityApp extends StatelessWidget {
  const ToddlerActivityApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Toddler Activity Finder',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.orange),
        useMaterial3: true,
      ),
      home: const ActivityListScreen(),
    );
  }
}

class ActivityListScreen extends StatefulWidget {
  const ActivityListScreen({super.key});

  @override
  State<ActivityListScreen> createState() => _ActivityListScreenState();
}

class _ActivityListScreenState extends State<ActivityListScreen> {
  Position? _currentPosition;
  bool _locationPermissionGranted = false;
  String _locationError = '';
  double _radiusMiles = 10;
  final List<double> _radiusOptions = [5, 10, 25];

  @override
  void initState() {
    super.initState();
    _getCurrentLocation();
  }

  Future<void> _getCurrentLocation() async {
    try {
      // Check if location services are enabled
      bool serviceEnabled = await Geolocator.isLocationServiceEnabled();
      if (!serviceEnabled) {
        setState(() {
          _locationError = 'Location services are disabled.';
        });
        return;
      }

      // Check location permissions
      LocationPermission permission = await Geolocator.checkPermission();
      if (permission == LocationPermission.denied) {
        permission = await Geolocator.requestPermission();
        if (permission == LocationPermission.denied) {
          setState(() {
            _locationError = 'Location permissions are denied.';
          });
          return;
        }
      }

      if (permission == LocationPermission.deniedForever) {
        setState(() {
          _locationError = 'Location permissions are permanently denied.';
        });
        return;
      }

      // Get current position
      Position position = await Geolocator.getCurrentPosition(
        desiredAccuracy: LocationAccuracy.high,
      );

      setState(() {
        _currentPosition = position;
        _locationPermissionGranted = true;
        _locationError = '';
      });
    } catch (e) {
      setState(() {
        _locationError = 'Error getting location: $e';
      });
    }
  }

  // Constants
  static const double _metersToMiles = 1609.344;

  double? _calculateDistance(double activityLat, double activityLon) {
    if (_currentPosition == null) return null;
    // Guard invalid coordinates (defaults like 0.0)
    if (activityLat == 0.0 && activityLon == 0.0) return null;

    // Validate coordinate ranges
    if (activityLat < -90 ||
        activityLat > 90 ||
        activityLon < -180 ||
        activityLon > 180) {
      return null;
    }

    try {
      // Distance in meters
      double distanceInMeters = Geolocator.distanceBetween(
        _currentPosition!.latitude,
        _currentPosition!.longitude,
        activityLat,
        activityLon,
      );

      // Convert to miles
      return distanceInMeters / _metersToMiles;
    } catch (e) {
      debugPrint('Error calculating distance: $e');
      return null;
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text("Toddler Activities"),
        actions: [
          if (_locationError.isNotEmpty)
            IconButton(
              icon: const Icon(Icons.location_off),
              onPressed: () {
                showDialog(
                  context: context,
                  builder: (context) => AlertDialog(
                    title: const Text('Location Error'),
                    content: Text(_locationError),
                    actions: [
                      TextButton(
                        onPressed: () {
                          Navigator.pop(context);
                          _getCurrentLocation();
                        },
                        child: const Text('Retry'),
                      ),
                      TextButton(
                        onPressed: () => Navigator.pop(context),
                        child: const Text('OK'),
                      ),
                    ],
                  ),
                );
              },
            ),
          if (_locationPermissionGranted && _currentPosition != null)
            IconButton(
              icon: const Icon(Icons.my_location),
              onPressed: _getCurrentLocation,
            ),
        ],
      ),
      body: StreamBuilder<QuerySnapshot>(
        stream: _activitiesTodayAndFuture(),
        builder: (context, snapshot) {
          Widget content;

          if (snapshot.hasError) {
            content = Center(
              child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  const Icon(Icons.error_outline, size: 48, color: Colors.red),
                  const SizedBox(height: 16),
                  Text(
                    'Error loading activities',
                    style: Theme.of(context).textTheme.titleMedium,
                  ),
                  const SizedBox(height: 8),
                  Text(
                    snapshot.error.toString(),
                    style: Theme.of(context).textTheme.bodySmall,
                    textAlign: TextAlign.center,
                  ),
                  const SizedBox(height: 16),
                  ElevatedButton.icon(
                    onPressed: () {
                      // Trigger a rebuild by calling setState
                      setState(() {});
                    },
                    icon: const Icon(Icons.refresh),
                    label: const Text('Retry'),
                  ),
                ],
              ),
            );
          } else if (!snapshot.hasData) {
            content = const Center(child: CircularProgressIndicator());
          } else {
            final docs = snapshot.data!.docs;

            // Convert to Activity objects with error handling
            var activities = <Activity>[];
            for (final doc in docs) {
              try {
                final activity = Activity.fromFirestore(
                  doc.data() as Map<String, dynamic>,
                  doc.id,
                );
                activities.add(activity);
              } catch (e) {
                // Log error but continue processing other activities
                // In production, consider logging to crash reporting service
                debugPrint('Failed to parse activity ${doc.id}: $e');
              }
            }

            // Filter and sort by distance if we have location
            // Cache distances to avoid recalculating
            final distanceMap = <String, double?>{};
            if (_currentPosition != null) {
              final radiusMiles = _radiusMiles;
              final activitiesWithDistance = activities
                  .map((a) {
                    final dist = _calculateDistance(a.latitude, a.longitude);
                    // Store distance in map for later use
                    distanceMap[a.id] = dist;
                    return (activity: a, distance: dist);
                  })
                  .where(
                    (item) =>
                        item.distance != null && item.distance! <= radiusMiles,
                  )
                  .toList();

              // Sort by distance
              activitiesWithDistance.sort((a, b) {
                final distA = a.distance ?? double.infinity;
                final distB = b.distance ?? double.infinity;
                return distA.compareTo(distB);
              });

              // Update activities list (distances already stored in map)
              activities = activitiesWithDistance
                  .map((item) => item.activity)
                  .toList();
            }

            if (activities.isEmpty) {
              final nearbyMsg = _currentPosition == null
                  ? 'No activities found. Enable location to filter by distance.'
                  : 'No activities found within ${_radiusMiles.toStringAsFixed(0)} miles.';
              content = Center(child: Text(nearbyMsg));
            } else {
              content = ListView.builder(
                padding: const EdgeInsets.all(16),
                itemCount: activities.length,
                itemBuilder: (context, index) {
                  final activity = activities[index];
                  final distance = distanceMap[activity.id];

                  return ActivityCard(activity: activity, distance: distance);
                },
              );
            }
          }

          final filterBar = Padding(
            padding: const EdgeInsets.fromLTRB(16, 12, 16, 0),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                const Text(
                  'Within radius',
                  style: TextStyle(fontWeight: FontWeight.w600),
                ),
                DropdownButton<double>(
                  value: _radiusMiles,
                  items: _radiusOptions
                      .map(
                        (r) => DropdownMenuItem(
                          value: r,
                          child: Text('${r.toStringAsFixed(0)} mi'),
                        ),
                      )
                      .toList(),
                  onChanged: (r) {
                    if (r == null) return;
                    setState(() {
                      _radiusMiles = r;
                    });
                  },
                ),
              ],
            ),
          );

          return Column(
            children: [
              filterBar,
              const SizedBox(height: 8),
              Expanded(child: content),
            ],
          );
        },
      ),
    );
  }
}

Stream<QuerySnapshot> _activitiesTodayAndFuture() {
  final now = DateTime.now();
  final todayStart = DateTime(now.year, now.month, now.day);
  final todayStartSec = todayStart.millisecondsSinceEpoch ~/ 1000;

  return FirebaseFirestore.instance
      .collection('activities')
      .where('startTime', isGreaterThanOrEqualTo: todayStartSec)
      .orderBy('startTime', descending: false)
      .snapshots();
}

class ActivityCard extends StatelessWidget {
  final Activity activity;
  final double? distance;

  const ActivityCard({super.key, required this.activity, this.distance});

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final startDateTime = DateTime.fromMillisecondsSinceEpoch(
      activity.startTime * 1000,
    );
    final DateTime? endDateTime = activity.endTime > 0
        ? DateTime.fromMillisecondsSinceEpoch(activity.endTime * 1000)
        : null;

    return Card(
      margin: const EdgeInsets.only(bottom: 16),
      elevation: 2,
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
      child: InkWell(
        onTap: () {
          // TODO: Navigate to activity details
        },
        borderRadius: BorderRadius.circular(12),
        child: Padding(
          padding: const EdgeInsets.all(16),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              // Title and badges row
              Row(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Expanded(
                    child: Text(
                      activity.title,
                      style: theme.textTheme.titleLarge?.copyWith(
                        fontWeight: FontWeight.bold,
                      ),
                    ),
                  ),
                  const SizedBox(width: 8),
                  if (activity.isFree)
                    _buildBadge('FREE', Colors.green, Icons.attach_money),
                ],
              ),
              const SizedBox(height: 8),

              // Venue with icon
              Row(
                children: [
                  Icon(
                    activity.isIndoor ? Icons.home : Icons.park,
                    size: 16,
                    color: theme.colorScheme.secondary,
                  ),
                  const SizedBox(width: 4),
                  Expanded(
                    child: Text(
                      activity.venue,
                      style: theme.textTheme.bodyMedium?.copyWith(
                        color: theme.colorScheme.secondary,
                      ),
                    ),
                  ),
                ],
              ),
              const SizedBox(height: 12),

              // Time and age range info
              Wrap(
                spacing: 16,
                runSpacing: 8,
                children: [
                  _buildInfoChip(
                    Icons.event,
                    _formatDate(startDateTime),
                    theme,
                  ),
                  _buildInfoChip(
                    Icons.access_time,
                    _formatTimeOrRange(startDateTime, endDateTime),
                    theme,
                  ),
                  _buildInfoChip(Icons.child_care, activity.ageRange, theme),
                  if (activity.requiresBooking)
                    _buildInfoChip(
                      Icons.event_available,
                      'Booking Required',
                      theme,
                    ),
                ],
              ),

              // Description if available
              if (activity.description != null &&
                  activity.description!.isNotEmpty) ...[
                const SizedBox(height: 12),
                Text(
                  activity.description!,
                  maxLines: 2,
                  overflow: TextOverflow.ellipsis,
                  style: theme.textTheme.bodyMedium,
                ),
              ],

              const SizedBox(height: 12),

              // Distance and action button
              Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  Row(
                    children: [
                      Icon(
                        Icons.location_on,
                        size: 16,
                        color: theme.colorScheme.primary,
                      ),
                      const SizedBox(width: 4),
                      Text(
                        distance != null
                            ? 'Distance: ${distance!.toStringAsFixed(1)} mi'
                            : 'Distance: -- mi',
                        style: theme.textTheme.bodySmall?.copyWith(
                          color: theme.colorScheme.primary,
                          fontWeight: distance != null && distance! < 2
                              ? FontWeight.bold
                              : FontWeight.normal,
                        ),
                      ),
                    ],
                  ),
                  Icon(
                    Icons.arrow_forward_ios,
                    size: 16,
                    color: theme.colorScheme.outline,
                  ),
                ],
              ),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildBadge(String label, Color color, IconData icon) {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
      decoration: BoxDecoration(
        color: color.withOpacity(0.1),
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: color, width: 1),
      ),
      child: Row(
        mainAxisSize: MainAxisSize.min,
        children: [
          Icon(icon, size: 14, color: color),
          const SizedBox(width: 4),
          Text(
            label,
            style: TextStyle(
              fontSize: 12,
              fontWeight: FontWeight.bold,
              color: color,
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildInfoChip(IconData icon, String label, ThemeData theme) {
    return Row(
      mainAxisSize: MainAxisSize.min,
      children: [
        Icon(icon, size: 16, color: theme.colorScheme.onSurfaceVariant),
        const SizedBox(width: 4),
        Text(
          label,
          style: theme.textTheme.bodySmall?.copyWith(
            color: theme.colorScheme.onSurfaceVariant,
          ),
        ),
      ],
    );
  }

  String _formatTimeOrRange(DateTime start, DateTime? end) {
    String hhmm(DateTime d) =>
        '${d.hour}:${d.minute.toString().padLeft(2, '0')}';
    if (end == null) return hhmm(start);
    return '${hhmm(start)} - ${hhmm(end)}';
  }

  String _formatDate(DateTime dt) {
    const months = [
      'Jan',
      'Feb',
      'Mar',
      'Apr',
      'May',
      'Jun',
      'Jul',
      'Aug',
      'Sep',
      'Oct',
      'Nov',
      'Dec',
    ];
    final month = months[dt.month - 1];
    return '$month ${dt.day}, ${dt.year}';
  }
}
