import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:geolocator/geolocator.dart';
import 'firebase_options.dart'; // This file was generated by flutterfire configure
import 'models/activity.dart'; // Ensure this matches your model file path

void main() async {
  // 1. Ensure Flutter bindings are initialized before Firebase
  WidgetsFlutterBinding.ensureInitialized();

  // 2. Initialize Firebase using the generated options
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  runApp(const ToddlerActivityApp());
}

class ToddlerActivityApp extends StatelessWidget {
  const ToddlerActivityApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Toddler Activity Finder',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.orange),
        useMaterial3: true,
      ),
      home: const ActivityListScreen(),
    );
  }
}

class ActivityListScreen extends StatefulWidget {
  const ActivityListScreen({super.key});

  @override
  State<ActivityListScreen> createState() => _ActivityListScreenState();
}

class _ActivityListScreenState extends State<ActivityListScreen> {
  Position? _currentPosition;
  bool _locationPermissionGranted = false;
  String _locationError = '';

  @override
  void initState() {
    super.initState();
    _getCurrentLocation();
  }

  Future<void> _getCurrentLocation() async {
    try {
      // Check if location services are enabled
      bool serviceEnabled = await Geolocator.isLocationServiceEnabled();
      if (!serviceEnabled) {
        setState(() {
          _locationError = 'Location services are disabled.';
        });
        return;
      }

      // Check location permissions
      LocationPermission permission = await Geolocator.checkPermission();
      if (permission == LocationPermission.denied) {
        permission = await Geolocator.requestPermission();
        if (permission == LocationPermission.denied) {
          setState(() {
            _locationError = 'Location permissions are denied.';
          });
          return;
        }
      }

      if (permission == LocationPermission.deniedForever) {
        setState(() {
          _locationError = 'Location permissions are permanently denied.';
        });
        return;
      }

      // Get current position
      Position position = await Geolocator.getCurrentPosition(
        desiredAccuracy: LocationAccuracy.high,
      );

      setState(() {
        _currentPosition = position;
        _locationPermissionGranted = true;
        _locationError = '';
      });
    } catch (e) {
      setState(() {
        _locationError = 'Error getting location: $e';
      });
    }
  }

  double? _calculateDistance(double activityLat, double activityLon) {
    if (_currentPosition == null) return null;

    // Distance in meters
    double distanceInMeters = Geolocator.distanceBetween(
      _currentPosition!.latitude,
      _currentPosition!.longitude,
      activityLat,
      activityLon,
    );

    // Convert to kilometers
    return distanceInMeters / 1000;
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text("Toddler Activities"),
        actions: [
          if (_locationError.isNotEmpty)
            IconButton(
              icon: const Icon(Icons.location_off),
              onPressed: () {
                showDialog(
                  context: context,
                  builder: (context) => AlertDialog(
                    title: const Text('Location Error'),
                    content: Text(_locationError),
                    actions: [
                      TextButton(
                        onPressed: () {
                          Navigator.pop(context);
                          _getCurrentLocation();
                        },
                        child: const Text('Retry'),
                      ),
                      TextButton(
                        onPressed: () => Navigator.pop(context),
                        child: const Text('OK'),
                      ),
                    ],
                  ),
                );
              },
            ),
          if (_locationPermissionGranted && _currentPosition != null)
            IconButton(
              icon: const Icon(Icons.my_location),
              onPressed: _getCurrentLocation,
            ),
        ],
      ),
      // StreamBuilder is the "magic" that listens to your DB in real-time
      body: StreamBuilder<QuerySnapshot>(
        stream: FirebaseFirestore.instance.collection('activities').snapshots(),
        builder: (context, snapshot) {
          if (!snapshot.hasData) {
            return const Center(child: CircularProgressIndicator());
          }

          final docs = snapshot.data!.docs;

          if (docs.isEmpty) {
            return const Center(child: Text('No activities found'));
          }

          // Convert to Activity objects
          final activities = docs.map((doc) {
            return Activity.fromFirestore(
              doc.data() as Map<String, dynamic>,
              doc.id,
            );
          }).toList();

          // Sort by distance if location is available
          if (_currentPosition != null) {
            activities.sort((a, b) {
              final distA =
                  _calculateDistance(a.latitude, a.longitude) ??
                  double.infinity;
              final distB =
                  _calculateDistance(b.latitude, b.longitude) ??
                  double.infinity;
              return distA.compareTo(distB);
            });
          }

          return ListView.builder(
            padding: const EdgeInsets.all(16),
            itemCount: activities.length,
            itemBuilder: (context, index) {
              final activity = activities[index];
              final distance = _calculateDistance(
                activity.latitude,
                activity.longitude,
              );

              return ActivityCard(activity: activity, distance: distance);
            },
          );
        },
      ),
    );
  }
}

class ActivityCard extends StatelessWidget {
  final Activity activity;
  final double? distance;

  const ActivityCard({super.key, required this.activity, this.distance});

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final startDateTime = DateTime.fromMillisecondsSinceEpoch(
      activity.startTime * 1000,
    );
    final endDateTime = DateTime.fromMillisecondsSinceEpoch(
      activity.endTime * 1000,
    );

    return Card(
      margin: const EdgeInsets.only(bottom: 16),
      elevation: 2,
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
      child: InkWell(
        onTap: () {
          // TODO: Navigate to activity details
        },
        borderRadius: BorderRadius.circular(12),
        child: Padding(
          padding: const EdgeInsets.all(16),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              // Title and badges row
              Row(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Expanded(
                    child: Text(
                      activity.title,
                      style: theme.textTheme.titleLarge?.copyWith(
                        fontWeight: FontWeight.bold,
                      ),
                    ),
                  ),
                  const SizedBox(width: 8),
                  if (activity.isFree)
                    _buildBadge('FREE', Colors.green, Icons.attach_money),
                ],
              ),
              const SizedBox(height: 8),

              // Venue with icon
              Row(
                children: [
                  Icon(
                    activity.isIndoor ? Icons.home : Icons.park,
                    size: 16,
                    color: theme.colorScheme.secondary,
                  ),
                  const SizedBox(width: 4),
                  Expanded(
                    child: Text(
                      activity.venue,
                      style: theme.textTheme.bodyMedium?.copyWith(
                        color: theme.colorScheme.secondary,
                      ),
                    ),
                  ),
                ],
              ),
              const SizedBox(height: 12),

              // Time and age range info
              Wrap(
                spacing: 16,
                runSpacing: 8,
                children: [
                  _buildInfoChip(
                    Icons.access_time,
                    _formatTimeRange(startDateTime, endDateTime),
                    theme,
                  ),
                  _buildInfoChip(Icons.child_care, activity.ageRange, theme),
                  if (activity.requiresBooking)
                    _buildInfoChip(
                      Icons.event_available,
                      'Booking Required',
                      theme,
                    ),
                ],
              ),

              // Description if available
              if (activity.description != null &&
                  activity.description!.isNotEmpty) ...[
                const SizedBox(height: 12),
                Text(
                  activity.description!,
                  maxLines: 2,
                  overflow: TextOverflow.ellipsis,
                  style: theme.textTheme.bodyMedium,
                ),
              ],

              const SizedBox(height: 12),

              // Distance and action button
              Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  Row(
                    children: [
                      Icon(
                        Icons.location_on,
                        size: 16,
                        color: theme.colorScheme.primary,
                      ),
                      const SizedBox(width: 4),
                      Text(
                        distance != null
                            ? 'Distance: ${distance!.toStringAsFixed(1)} km'
                            : 'Distance: -- km',
                        style: theme.textTheme.bodySmall?.copyWith(
                          color: theme.colorScheme.primary,
                          fontWeight: distance != null && distance! < 2
                              ? FontWeight.bold
                              : FontWeight.normal,
                        ),
                      ),
                    ],
                  ),
                  Icon(
                    Icons.arrow_forward_ios,
                    size: 16,
                    color: theme.colorScheme.outline,
                  ),
                ],
              ),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildBadge(String label, Color color, IconData icon) {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
      decoration: BoxDecoration(
        color: color.withOpacity(0.1),
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: color, width: 1),
      ),
      child: Row(
        mainAxisSize: MainAxisSize.min,
        children: [
          Icon(icon, size: 14, color: color),
          const SizedBox(width: 4),
          Text(
            label,
            style: TextStyle(
              fontSize: 12,
              fontWeight: FontWeight.bold,
              color: color,
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildInfoChip(IconData icon, String label, ThemeData theme) {
    return Row(
      mainAxisSize: MainAxisSize.min,
      children: [
        Icon(icon, size: 16, color: theme.colorScheme.onSurfaceVariant),
        const SizedBox(width: 4),
        Text(
          label,
          style: theme.textTheme.bodySmall?.copyWith(
            color: theme.colorScheme.onSurfaceVariant,
          ),
        ),
      ],
    );
  }

  String _formatTimeRange(DateTime start, DateTime end) {
    final startStr = '${start.hour}:${start.minute.toString().padLeft(2, '0')}';
    final endStr = '${end.hour}:${end.minute.toString().padLeft(2, '0')}';
    return '$startStr - $endStr';
  }
}
